url: http://www.marensiegel.de
baseurl:

# Site settings
title: Maren Siegel • Packaging, Corporate & Grafik Design
email: m@marensiegel.de
description: |-
  Maren Siegel arbeitet als freiberufliche Designerin aus Berlin heraus.
  Sie ist spezialisiert auf Packaging Design, Corporate Design und Grafik Design.

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: true
permalink: pretty
